---
name: Copy to S3
on:
  push:
    branches:
      - main
env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_DEFAULT_OUTPUT: json
jobs:
  copy-to-s3:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub’s OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-west-2
        ## the following creates an ARN based on the values entered into github secrets
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.COPY_TO_S3_ROLE }}
    - name: Copy files to S3
      run: |
        aws s3 sync . s3://mibeard-dev-files/saas-boost-examples/
...